Admin view:<br/>
<!--
<a href="javascript:sic.loadModule({moduleName:'testModule'});">Load TestModule</a><br />
<a href="javascript:sic.callMethod({moduleName:'testModule', methodName:'testMethod'});">Run TestModule.testMethod()</a>
-->
<a href="javascript:sic.loadModule({moduleName:'systemModule'});">Load SystemModule</a><br />
<a href="javascript:sic.callMethod({moduleName:'systemModule', methodName:'test'});">Run SystemtModule.test()</a>

<br/>
<br/>

<div id="pageHolder"></div>