<div id="container"></div>
<script type="text/javascript">
    $(function(){
        var panel = new sic.widget.sicPanel({parent:$("#container")});
        var form = new sic.widget.sicForm({parent:panel.firstGroup.content.selector});
        form.addInput({name:"username", type:"text", label:"Username"});
        form.addInput({name:"password", type:"password", label:""});
        form.addInput({name:"login", type:"button"})
            .setGradient("blue").selector.click(function(e){
                $.post("/login", form.getValue(), function(data) {
                    var d = JSON.parse(data);
                    if(d.status) window.location = "/";
                });
            });

    });
</script>