<div id="container"></div>
<script type="text/javascript">
    $(function(){
        //var statusDiv = new sic.widget.sicElement({parent:$("#container"), tagClass:"statusDiv"});
        //statusDiv.selector.html("Login");

        var panel = new sic.widget.sicPanel({parent:$("#container")});
        var panelGroup = panel.addGroup("Login");
        panelGroup.header.selector.addClass("statusDiv");

        var statusDiv = panelGroup.header;
        var form = new sic.widget.sicForm({parent:panelGroup.content.selector});
        form.addInput({name:"username", type:"text", placeholder:"Username...", caption:"", focus: true});
        form.addInput({name:"password", type:"password", placeholder:"Password...", caption:""});
        form.addInput({name:"login", type:"submit", value:"Login", gradient:"blue"});
        form.onSubmit(function(e){
            sic.loading.show();
            statusDiv.selector.removeClass("errorDiv");
            statusDiv.selector.html("Login...");
            $.post("/login", form.getValue(), function(data) {
                var d = JSON.parse(data);
                if(d.status){
                    window.location = "/";
                } else {
                    statusDiv.selector.addClass("errorDiv");
                    statusDiv.selector.html('Login incorrect.');
                    sic.loading.hide();
                }
            });
        });
    });
</script>