<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>
    <script src="/lib/jquery/jquery-2.1.1.js"></script>

    <script src="/js/sic/sic.js"></script>
    <script src="/js/sic/util.js"></script>
    <script src="/js/sic/widget/sicElement.js"></script>
    <script src="/js/sic/widget/sicTabPage.js"></script>

    <link rel="stylesheet" href="/lib/zurb/css/normalize.css" />
    <link rel="stylesheet" href="/lib/zurb/css/foundation.css" />
    <!--
    <script src="/lib/zurb/js/vendor/custom.modernizr.js"></script>
    -->
    <link rel="stylesheet" href="/css/standard.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/sic.css" type="text/css" media="screen" />
</head>


<body>

<div id="header" class="row">
    <table cellpadding="0" cellspacing="0" width="100%">
        <tr>
            <td ><a href="/" title="Slovenian Index of citation - Admin"><img src="/img/logo.png" /></a></td>
            <td align="right" class="pr_20" style="vertical-align:bottom;">
                <a href="/login">Login</a>
            </td>
        </tr>
    </table>
</div>

<div id="navigation" class="row">
    <div>
        <ul>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'searchModule'});">Search</a>
            </li>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'systemModule'});">System</a>
            </li>
            <li class="mainMenuList">
                <a href="#">Edit page</a>
            </li>
        </ul>
    </div>
</div>

<div id="content" class="row">
    <?php echo $this->layout()->content; ?>
</div>

</body>
</html>
