<!DOCTYPE html>
<!DOCTYPE html>
<html>
<head>

    <link rel="icon" type="image/png" href="/img/icon.png">

    <script src="/lib/jquery/jquery-2.1.1.js"></script>

    <script src="/js/sic/sic.js"></script>
    <script src="/js/sic/util.js"></script>
    <script src="/js/sic/object/sicEventBase.js"></script>
    <script src="/js/sic/object/sicMessageTunnel.js"></script>
    <script src="/js/sic/widget/sicElement.js"></script>
    <script src="/js/sic/widget/sicTabPage.js"></script>
    <script src="/js/sic/widget/sicDataTable.js"></script>
    <script src="/js/sic/widget/sicPanel.js"></script>
    <script src="/js/sic/widget/sicForm.js"></script>
    <script src="/js/sic/widget/sicInput.js"></script>
    <script src="/js/sic/widget/sicInputArray.js"></script>
    <script src="/js/sic/widget/sicMultiSelect.js"></script>

    <link rel="stylesheet" href="/lib/zurb/css/normalize.css" />
    <link rel="stylesheet" href="/lib/zurb/css/foundation.css" />
    <!--
    <script src="/lib/zurb/js/vendor/custom.modernizr.js"></script>
    -->

    <link rel="stylesheet" href="/css/gradients.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/standard.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/sic.css" type="text/css" media="screen" />
    <link rel="stylesheet" href="/css/modules.css" type="text/css" media="screen" />
</head>


<body>

<div id="header" class="">
    <table cellpadding="0" cellspacing="0" width="100%" class="logoTable">
        <tr>
            <td ><a href="/" title="Slovenian Index of citation - Admin"><img src="/img/logo2.png" class="logoImage"/><img src="/img/loading-book.gif" class="loadingGif" id="loadingGif" style="display:none;"><div class="mainTitle">Slovenian Index of citation v2</div></a></td>
            <td align="right" class="pr_20" style="vertical-align:bottom;">
                <?php if($this->hasIdentity){ ?>
                    <span class="loginName"><?php echo $this->username; ?> (<a href="/logout">Logout</a>)</span>
                <?php } ?>
                <?php if(!$this->hasIdentity){ ?>
                    <a href="/login">Login</a>
                <?php } ?>
            </td>
        </tr>
    </table>
</div>

<?php if($this->hasIdentity){ ?>
<div id="navigation" class="">
    <div>
        <ul>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'Pub/PubSearch'});">Search</a>
            </li>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'System/Dashboard', newTab:'System'});">System</a>
            </li>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'User/UserList', newTab:'Users'});">Users</a>
            </li>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'Test/Cobiss'});">Cobiss</a>
            </li>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'Pub/PubList', newTab:'Publications'});">Publications</a>
            </li>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'Project/ProjectList', newTab:'Projects'});">Projects</a>
            </li>
            <li class="mainMenuList">
                <a href="javascript:sic.loadModule({moduleName:'Test/WidgetTest'});">WidgetTest</a>
            </li>
        </ul>
    </div>
</div>
<?php } ?>

<div id="content" class="">
    <div id="pageHolder"></div>
    <div id="primaryPage">
        <?php echo $this->layout()->content; ?>
    </div>
</div>

</body>
</html>
